### ISSUE TITLE
Is there a setup guide for using this plugin with `L3MON4D3/LuaSnip`?

### ISSUE THREAD

**Issue by surmish** [rafamadriz/friendly-snippets#33]
The README says it should be compatible but I don't see any setup instructions.

**Comment by rafamadriz** [comment]
Sorry about that, you're right, there should be some setup example. Here the link where they explain how to use VsCode snippets in with LuaSnip that https://github.com/L3MON4D3/LuaSnip/blob/72323c10fe2d91695f7593e572496ab9f004afee/Examples/snippets.lua#L263-L274

**Comment by surmish** [comment]
I copied the last line there

`require("luasnip/loaders/from_vscode").lazy_load() -- You can pass { path = "./my-snippets/"} as well`

But see an error in luasnip when I navigate to the snipped in the list that shows up.

`Error executing vim.schedule lua callback: .../pack/packer/start/nvim-compe/lua/compe_luasnip/init.lua:27: attempt to concatenate a table value`

**Comment by rafamadriz** [comment]
Oh yeah that's a problem with the compe source for luasnip, should get fixed by hrsh7th/nvim-compe#457

**Comment by surmish** [comment]
Thanks, you can close the ticket. Will follow that issue.

**Comment by surmish** [comment]
I still can't select the snippet

![image](https://user-images.githubusercontent.com/33273194/124965806-60354a80-dfd7-11eb-9df6-dafc9b51d100.png)

I am not sure how to confirm the selection. Ctrl J, Y or any other key doesn't work. I tried arrow keys, shift, tab, they only complete the keyword, not the snippet associated with it.

Also, it's not clear what is being shown in the floating window. Why is there a [cpp] and what is the double line underneath?

**Comment by L3MON4D3** [comment]
You'll most likely have to bind compes' confirm, see `:h compe`. As for the [cpp], that's the current doc-window for the luasnip source in compe (not very pretty, I know :sweat_smile:).

**Comment by surmish** [comment]
Thanks @L3MON4D3, that worked, I was under the impressions there'd be some defaults. Do you know, within a snippet, how to jump to different sections? In Vim and earlier plugins, C-J would take me to the 4 different sections in a `for` snippet.

**Comment by L3MON4D3** [comment]
Luasnip doesn't provide defaults, but you can see what to set [here](https://github.com/L3MON4D3/LuaSnip/blob/master/README.md)
